### ISSUE TITLE
Using offline database.

### ISSUE THREAD

**Issue by xCoDiS** [Blaxor/Restrict-Creative#1]
[19:44:18 INFO]: [RestrictCreative] Enabling RestrictCreative v5.1
[19:44:22 INFO]: Using offline database.
[19:44:22 WARN]: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (table RestrictCreative already exists)
[19:44:22 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:909)
[19:44:22 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:921)
[19:44:22 WARN]:        at org.sqlite.core.DB.throwex(DB.java:886)
[19:44:22 WARN]:        at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
[19:44:22 WARN]:        at org.sqlite.core.NativeDB.prepare(NativeDB.java:127)
[19:44:22 WARN]:        at org.sqlite.core.DB.prepare(DB.java:227)
[19:44:22 WARN]:        at org.sqlite.jdbc3.JDBC3Statement.execute(JDBC3Statement.java:60)
[19:44:22 WARN]:        at ro.deiutzblaxo.RestrictCreative.mySQL.MySQLHandler.createNewTableOffline(MySQLHandler.java:120)
[19:44:22 WARN]:        at ro.deiutzblaxo.RestrictCreative.mySQL.MySQLHandler.mysqlopenConnection(MySQLHandler.java:81)
[19:44:22 WARN]:        at ro.deiutzblaxo.RestrictCreative.mySQL.MySQLHandler.setupConnection(MySQLHandler.java:43)
[19:44:22 WARN]:        at ro.deiutzblaxo.RestrictCreative.mySQL.MySQLHandler.<init>(MySQLHandler.java:27)
[19:44:22 WARN]:        at ro.deiutzblaxo.RestrictCreative.Main.onEnable(Main.java:44)
[19:44:22 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[19:44:22 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[19:44:22 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[19:44:22 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[19:44:22 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[19:44:22 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[19:44:22 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[19:44:22 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[19:44:22 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[19:44:22 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[19:44:22 WARN]:        at java.lang.Thread.run(Unknown Source)
[19:44:27 INFO]: Using offline database.
[19:44:27 WARN]: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (table RestrictCreative already exists)
[19:44:27 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:909)
[19:44:27 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:921)
[19:44:27 WARN]:        at org.sqlite.core.DB.throwex(DB.java:886)
[19:44:27 WARN]:        at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
[19:44:27 WARN]:        at org.sqlite.core.NativeDB.prepare(NativeDB.java:127)
[19:44:27 WARN]:        at org.sqlite.core.DB.prepare(DB.java:227)
[19:44:27 WARN]:        at org.sqlite.jdbc3.JDBC3Statement.execute(JDBC3Statement.java:60)
[19:44:27 WARN]:        at ro.deiutzblaxo.RestrictCreative.mySQL.MySQLHandler.createNewTableOffline(MySQLHandler.java:120)
[19:44:27 WARN]:        at ro.deiutzblaxo.RestrictCreative.mySQL.MySQLHandler.mysqlopenConnection(MySQLHandler.java:81)
[19:44:27 WARN]:        at ro.deiutzblaxo.RestrictCreative.mySQL.MySQLHandler.setupConnection(MySQLHandler.java:43)
[19:44:27 WARN]:        at ro.deiutzblaxo.RestrictCreative.Main.onEnable(Main.java:46)
[19:44:27 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[19:44:27 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[19:44:27 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[19:44:27 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[19:44:27 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[19:44:27 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[19:44:27 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[19:44:27 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[19:44:27 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[19:44:27 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[19:44:27 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by Blaxor** [comment]
Hi try to rename /delete the data base which is already existing and let the plugin to create it . after the plugin is creating his database try to move everything from the old database to the new one! if this don`t work try to change the name of table from plugin`s config
